analytics: {}
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.756757
  lightness: 0.796748
  rhythmicContrast: 0
  saturation: 0.215372
cta: {}
layout_spectrum: 0.99882
name: FastLife
opengraph: {}
purpose: []
typography_spectrum: 0.22597
